"""Per-user LSP workspace directories (seeded from packaged ``data/lsp``)."""

from __future__ import annotations

import os
import shutil
from pathlib import Path

from services.lsp.pm_require_types import pm_require_index_path


def _repo_data_lsp() -> Path:
    return Path(__file__).resolve().parents[4] / "data" / "lsp"


def user_lsp_root() -> Path:
    """Return ``~/.local/share/postmark/lsp-workspace`` (created)."""
    base = Path(os.environ.get("XDG_DATA_HOME", Path.home() / ".local" / "share"))
    root = base / "postmark" / "lsp-workspace"
    root.mkdir(parents=True, exist_ok=True)
    return root


_DENO_CONFIG = """{
  "compilerOptions": {
    "checkJs": true,
    "allowJs": true,
    "noImplicitAny": false,
    "strict": false,
    "types": ["./ambient_pm.d.ts"]
  },
  "nodeModulesDir": "auto",
  "include": ["**/*.ts", "**/*.js", "ambient_pm.d.ts", "pm_require_index.ts"]
}
"""

_PM_REQUIRE_INDEX_STUB = """/** Auto-generated by Postmark — do not edit. */

// No pm.require npm/jsr specifiers detected.
export {};
"""


def ensure_js_workspace() -> Path:
    """Seed JS workspace with the ``pm.d.ts`` stub and a ``deno.json``.

    The ``deno.json`` enables ``checkJs`` so Deno LSP type-checks
    ``.js`` buffers (default behaviour only checks ``.ts``). Also
    seeds an empty ``pm_require_index.ts`` for ``pm.require`` overloads.
    """
    ws = user_lsp_root() / "js"
    ws.mkdir(parents=True, exist_ok=True)
    # Drop any tsconfig left from earlier installs — its ``lib`` setting
    # would override Deno's defaults and hide ``console``.
    legacy_ts = ws / "tsconfig.json"
    if legacy_ts.is_file():
        legacy_ts.unlink()
    (ws / "deno.json").write_text(_DENO_CONFIG, encoding="utf-8")
    index_path = pm_require_index_path(ws)
    if not index_path.is_file():
        index_path.write_text(_PM_REQUIRE_INDEX_STUB, encoding="utf-8")
    from services.scripting.local_scripts_project.deno_config import ensure_ambient_pm

    ensure_ambient_pm(ws)
    stubs = _repo_data_lsp() / "stubs"
    dst_stubs = ws / "stubs"
    dst_stubs.mkdir(exist_ok=True)
    for name in ("pm.d.ts",):
        src = stubs / name
        if src.is_file():
            shutil.copy2(src, dst_stubs / name)
    return ws


def ensure_py_workspace() -> Path:
    """Seed Python workspace with ``pm.pyi``."""
    ws = user_lsp_root() / "py"
    ws.mkdir(parents=True, exist_ok=True)
    stubs = _repo_data_lsp() / "stubs"
    dst = ws / "stubs"
    dst.mkdir(exist_ok=True)
    src = stubs / "pm.pyi"
    if src.is_file():
        shutil.copy2(src, dst / "pm.pyi")
    return ws
