"""Per-type field specifications for all supported auth types.

Each key maps to a tuple of :class:`FieldSpec` descriptors that drive
the data-driven page builder in :mod:`auth_pages`.
"""

from __future__ import annotations

from ui.request.auth.auth_pages import FieldSpec

AUTH_FIELD_SPECS: dict[str, tuple[FieldSpec, ...]] = {
    "bearer": (FieldSpec("token", "Token", placeholder="Enter bearer token"),),
    "basic": (
        FieldSpec("username", "Username", placeholder="Username"),
        FieldSpec("password", "Password", kind="password", placeholder="Password"),
    ),
    "apikey": (
        FieldSpec("key", "Key", placeholder="Header or query parameter name"),
        FieldSpec("value", "Value", placeholder="API key value"),
        FieldSpec(
            "in",
            "Add to",
            kind="combo",
            options=("Header", "Query Params"),
            width=140,
            combo_map={"header": "Header", "query": "Query Params"},
            default="header",
        ),
    ),
    "digest": (
        FieldSpec("username", "Username", placeholder="Username"),
        FieldSpec("password", "Password", kind="password", placeholder="Password"),
        FieldSpec("realm", "Realm", placeholder="Realm", advanced=True),
        FieldSpec("nonce", "Nonce", placeholder="Server nonce", advanced=True),
        FieldSpec(
            "algorithm",
            "Algorithm",
            kind="combo",
            options=(
                "MD5",
                "MD5-sess",
                "SHA-256",
                "SHA-256-sess",
                "SHA-512-256",
                "SHA-512-256-sess",
            ),
            default="MD5",
            advanced=True,
        ),
        FieldSpec(
            "qop",
            "Quality of Protection",
            placeholder="auth or auth-int",
            advanced=True,
        ),
        FieldSpec("nonceCount", "Nonce Count", placeholder="00000001", advanced=True),
        FieldSpec("clientNonce", "Client Nonce", placeholder="Client nonce", advanced=True),
        FieldSpec("opaque", "Opaque", placeholder="Opaque string from server", advanced=True),
    ),
    "oauth1": (
        FieldSpec("consumerKey", "Consumer Key", placeholder="Consumer key"),
        FieldSpec(
            "consumerSecret",
            "Consumer Secret",
            kind="password",
            placeholder="Consumer secret",
        ),
        FieldSpec("token", "Access Token", placeholder="Access token"),
        FieldSpec("tokenSecret", "Token Secret", kind="password", placeholder="Token secret"),
        FieldSpec(
            "signatureMethod",
            "Signature Method",
            kind="combo",
            options=("HMAC-SHA1", "HMAC-SHA256", "PLAINTEXT", "RSA-SHA1"),
            default="HMAC-SHA1",
        ),
        FieldSpec(
            "addParamsToHeader",
            "Add auth data to",
            kind="combo",
            options=("Header", "Request URL"),
            combo_map={"true": "Header", "false": "Request URL"},
            default="true",
            save_as_bool=True,
        ),
        FieldSpec("timestamp", "Timestamp", placeholder="Auto-generated if empty", advanced=True),
        FieldSpec("nonce", "Nonce", placeholder="Auto-generated if empty", advanced=True),
        FieldSpec("version", "Version", placeholder="1.0", default="1.0", advanced=True),
        FieldSpec("realm", "Realm", placeholder="Realm (optional)", advanced=True),
    ),
    "oauth2": (
        FieldSpec("accessToken", "Access Token", placeholder="Paste your access token"),
        FieldSpec("headerPrefix", "Header Prefix", placeholder="Bearer", default="Bearer"),
        FieldSpec(
            "addTokenTo",
            "Add token to",
            kind="combo",
            options=("Header", "Query Params"),
            combo_map={"header": "Header", "queryParams": "Query Params"},
            default="header",
        ),
    ),
    "hawk": (
        FieldSpec("authId", "Hawk Auth ID", placeholder="Auth ID"),
        FieldSpec("authKey", "Hawk Auth Key", kind="password", placeholder="Auth key"),
        FieldSpec(
            "algorithm",
            "Algorithm",
            kind="combo",
            options=("sha256", "sha1"),
            default="sha256",
        ),
        FieldSpec("user", "User", placeholder="User (optional)", advanced=True),
        FieldSpec("nonce", "Nonce", placeholder="Auto-generated if empty", advanced=True),
        FieldSpec(
            "extraData",
            "Extra Data (ext)",
            placeholder="Application-specific data",
            advanced=True,
        ),
        FieldSpec("appId", "App ID", placeholder="App ID (optional)", advanced=True),
        FieldSpec("delegation", "Delegation", placeholder="Delegation token", advanced=True),
        FieldSpec("timestamp", "Timestamp", placeholder="Auto-generated if empty", advanced=True),
    ),
    "awsv4": (
        FieldSpec("accessKey", "Access Key", placeholder="AWS access key ID"),
        FieldSpec("secretKey", "Secret Key", kind="password", placeholder="AWS secret key"),
        FieldSpec("region", "AWS Region", placeholder="us-east-1", default="us-east-1"),
        FieldSpec("service", "Service Name", placeholder="e.g. s3, execute-api"),
        FieldSpec(
            "sessionToken",
            "Session Token",
            placeholder="Optional session token",
            advanced=True,
        ),
        FieldSpec(
            "addAuthDataTo",
            "Add auth data to",
            kind="combo",
            options=("Header", "Query Params"),
            combo_map={"header": "Header", "queryParams": "Query Params"},
            default="header",
            advanced=True,
        ),
    ),
    "jwt": (
        FieldSpec(
            "algorithm",
            "Algorithm",
            kind="combo",
            options=(
                "HS256",
                "HS384",
                "HS512",
                "RS256",
                "RS384",
                "RS512",
                "ES256",
                "ES384",
                "ES512",
                "PS256",
                "PS384",
                "PS512",
            ),
            default="HS256",
        ),
        FieldSpec("secret", "Secret", kind="password", placeholder="Secret key (HMAC)"),
        FieldSpec(
            "privateKey",
            "Private Key",
            kind="textarea",
            placeholder="RSA/EC private key in PEM format",
        ),
        FieldSpec("payload", "Payload", kind="textarea", placeholder='{"sub": "1234567890"}'),
        FieldSpec(
            "headers",
            "Custom Headers",
            kind="textarea",
            placeholder='{"kid": "my-key-id"}',
        ),
        FieldSpec(
            "isSecretBase64Encoded",
            "Secret is Base64 encoded",
            kind="combo",
            options=("No", "Yes"),
            combo_map={"false": "No", "true": "Yes"},
            default="false",
            save_as_bool=True,
        ),
        FieldSpec(
            "addTokenTo",
            "Add token to",
            kind="combo",
            options=("Header", "Query Params"),
            combo_map={"header": "Header", "queryParams": "Query Params"},
            default="header",
        ),
        FieldSpec("headerPrefix", "Header Prefix", placeholder="Bearer", default="Bearer"),
        FieldSpec("queryParamKey", "Query Param Key", placeholder="token", default="token"),
    ),
    "asap": (
        FieldSpec("issuer", "Issuer (iss)", placeholder="Issuer claim"),
        FieldSpec("subject", "Subject (sub)", placeholder="Subject claim"),
        FieldSpec("audience", "Audience (aud)", placeholder="Audience claim"),
        FieldSpec(
            "privateKey",
            "Private Key",
            kind="textarea",
            placeholder="RSA private key in PEM format",
        ),
        FieldSpec("kid", "Key ID (kid)", placeholder="Key identifier"),
        FieldSpec(
            "algorithm",
            "Algorithm",
            kind="combo",
            options=("RS256", "PS256"),
            default="RS256",
        ),
        FieldSpec("expiresIn", "Expires In (seconds)", placeholder="3600", default="3600"),
        FieldSpec(
            "claims",
            "Additional Claims",
            kind="textarea",
            placeholder='{"custom": "value"}',
        ),
    ),
    "ntlm": (
        FieldSpec("username", "Username", placeholder="Username"),
        FieldSpec("password", "Password", kind="password", placeholder="Password"),
        FieldSpec("domain", "Domain", placeholder="e.g. example.com", advanced=True),
        FieldSpec("workstation", "Workstation", placeholder="e.g. John-PC", advanced=True),
    ),
    "edgegrid": (
        FieldSpec("accessToken", "Access Token", placeholder="Access token"),
        FieldSpec("clientToken", "Client Token", placeholder="Client token"),
        FieldSpec(
            "clientSecret",
            "Client Secret",
            kind="password",
            placeholder="Client secret",
        ),
        FieldSpec("nonce", "Nonce", placeholder="Nonce", advanced=True),
        FieldSpec("timestamp", "Timestamp", placeholder="Timestamp", advanced=True),
        FieldSpec("baseURL", "Base URL", placeholder="Base URL", advanced=True),
        FieldSpec(
            "headersToSign",
            "Headers to Sign",
            placeholder="Headers to Sign",
            advanced=True,
        ),
        FieldSpec(
            "maxBody",
            "Max Body Size",
            placeholder="Max Body Size",
            default="131072",
            advanced=True,
            suffix="bytes",
        ),
    ),
}
