/** Generated by services.lsp.stubs_generator — do not edit. */

declare namespace pm {
  namespace collectionVariables {
    /** `clear` */
    function clear(...args: any[]): any;
    /** `get` */
    function get(...args: any[]): any;
    /** `has` */
    function has(...args: any[]): any;
    /** `replaceIn` */
    function replaceIn(...args: any[]): any;
    /** `set` */
    function set(...args: any[]): any;
    /** `toObject` */
    function toObject(...args: any[]): any;
    /** `unset` */
    function unset(...args: any[]): any;
  }
  namespace cookies {
    /** `get` */
    function get(...args: any[]): any;
    /** `getAll` */
    function getAll(...args: any[]): any;
  }
  namespace environment {
    /** `clear` */
    function clear(...args: any[]): any;
    /** `get` */
    function get(...args: any[]): any;
    /** `has` */
    function has(...args: any[]): any;
    /** `replaceIn` */
    function replaceIn(...args: any[]): any;
    /** `set` */
    function set(...args: any[]): any;
    /** `toObject` */
    function toObject(...args: any[]): any;
    /** `unset` */
    function unset(...args: any[]): any;
  }
  namespace execution {
    /** `setNextRequest` */
    function setNextRequest(...args: any[]): any;
    /** `skipRequest` */
    function skipRequest(...args: any[]): any;
  }
  /** `expect` */
  function expect(...args: any[]): any;
  namespace globals {
    /** `clear` */
    function clear(...args: any[]): any;
    /** `get` */
    function get(...args: any[]): any;
    /** `has` */
    function has(...args: any[]): any;
    /** `replaceIn` */
    function replaceIn(...args: any[]): any;
    /** `set` */
    function set(...args: any[]): any;
    /** `toObject` */
    function toObject(...args: any[]): any;
    /** `unset` */
    function unset(...args: any[]): any;
  }
  /** free-form `info` */
  const info: any;
  namespace iterationData {
    /** `get` */
    function get(...args: any[]): any;
    /** `has` */
    function has(...args: any[]): any;
    /** `toObject` */
    function toObject(...args: any[]): any;
  }
  /** free-form `request` */
  const request: any;
  /** `require` */
  function require(...args: any[]): any;
  /** free-form `response` */
  const response: any;
  /** `sendRequest` */
  function sendRequest(...args: any[]): any;
  /** `test` */
  function test(...args: any[]): any;
  namespace variables {
    /** `clear` */
    function clear(...args: any[]): any;
    /** `get` */
    function get(...args: any[]): any;
    /** `has` */
    function has(...args: any[]): any;
    /** `replaceIn` */
    function replaceIn(...args: any[]): any;
    /** `set` */
    function set(...args: any[]): any;
    /** `toObject` */
    function toObject(...args: any[]): any;
    /** `unset` */
    function unset(...args: any[]): any;
  }
}

declare namespace postman {
  /** `clearEnvironmentVariable` */
  function clearEnvironmentVariable(...args: any[]): any;
  /** `clearGlobalVariable` */
  function clearGlobalVariable(...args: any[]): any;
  /** `getEnvironmentVariable` */
  function getEnvironmentVariable(...args: any[]): any;
  /** `getGlobalVariable` */
  function getGlobalVariable(...args: any[]): any;
  /** `setEnvironmentVariable` */
  function setEnvironmentVariable(...args: any[]): any;
  /** `setGlobalVariable` */
  function setGlobalVariable(...args: any[]): any;
}

