"""Build ``data/app-wiki/index.md`` from user-guide and allowlisted scripting docs."""

from __future__ import annotations

import re
from pathlib import Path

from database.data_paths import project_root
from services.ai.chat.app_wiki.config import (
    SCRIPTING_ALLOWLIST,
    app_wiki_root,
    user_guide_root,
)


def _title_from_markdown(text: str, fallback: str) -> str:
    """Extract the first ``#`` heading or use *fallback*."""
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("# "):
            return stripped[2:].strip()
    return fallback


def _summary_from_markdown(text: str) -> str:
    """First non-empty paragraph after the title."""
    lines = text.splitlines()
    body_start = 0
    for i, line in enumerate(lines):
        if line.strip().startswith("# "):
            body_start = i + 1
            break
    paragraph: list[str] = []
    for line in lines[body_start:]:
        stripped = line.strip()
        if not stripped:
            if paragraph:
                break
            continue
        if stripped.startswith("#"):
            break
        paragraph.append(stripped)
    summary = " ".join(paragraph)
    summary = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", summary)
    if len(summary) > 160:
        return summary[:157] + "…"
    return summary or "User guide page."


def _section_label(rel_posix: str) -> str:
    """Derive a grouping label from a repo-relative path."""
    if rel_posix.startswith("docs/user-guide/"):
        parts = rel_posix.removeprefix("docs/user-guide/").split("/")
        return f"user-guide / {parts[0]}" if parts else "user-guide"
    if rel_posix.startswith("docs/scripting/"):
        return "scripting-api / prose"
    if rel_posix.startswith("docs/guides/"):
        return "scripting-api / prose"
    if rel_posix.startswith("data/app-wiki/scripting-api/"):
        return "scripting-api / quickref"
    return "other"


def collect_index_sources(root: Path | None = None) -> list[Path]:
    """Return sorted markdown sources that belong in the wiki index."""
    repo = root or project_root()
    sources: list[Path] = []
    ug = user_guide_root(repo)
    if ug.is_dir():
        sources.extend(sorted(ug.rglob("*.md")))
    for rel in SCRIPTING_ALLOWLIST:
        path = repo / rel
        if path.is_file():
            sources.append(path)
    api_dir = app_wiki_root(repo) / "scripting-api"
    if api_dir.is_dir():
        sources.extend(sorted(api_dir.glob("*.md")))
    return sources


def build_index_markdown(root: Path | None = None) -> str:
    """Generate the full ``index.md`` body."""
    repo = root or project_root()
    sources = collect_index_sources(repo)
    grouped: dict[str, list[tuple[str, str, str]]] = {}
    for path in sources:
        rel = path.relative_to(repo).as_posix()
        text = path.read_text(encoding="utf-8")
        title = _title_from_markdown(text, path.stem.replace("-", " ").title())
        summary = _summary_from_markdown(text)
        label = _section_label(rel)
        grouped.setdefault(label, []).append((rel, title, summary))

    lines = [
        "# Postmark app wiki index",
        "",
        "Generated by ``scripts/build_app_wiki.py``. Do not edit by hand.",
        "",
    ]
    for label in sorted(grouped.keys()):
        lines.append(f"## {label}")
        lines.append("")
        for rel, title, summary in sorted(grouped[label], key=lambda t: t[0]):
            lines.append(f"- `{rel}` — {title} — {summary}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_index(root: Path | None = None) -> Path:
    """Write ``data/app-wiki/index.md`` and return its path."""
    repo = root or project_root()
    out_dir = app_wiki_root(repo)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "index.md"
    out_path.write_text(build_index_markdown(repo), encoding="utf-8")
    return out_path
