"""Generate ``pm_require_index.ts`` and cache npm/jsr specifiers for Deno LSP."""

from __future__ import annotations

import contextlib
import json
import logging
import os
import subprocess
from pathlib import Path

from services.scripting.deno_runtime import _build_npmrc_text, _postmark_deno_user_cache_dir
from services.scripting.js_runtime import PmRequireSpec, _detect_pm_require_specs
from services.scripting.runtime_settings import RuntimeSettings

logger = logging.getLogger(__name__)

_INDEX_NAME = "pm_require_index.ts"
_CACHE_STATE_NAME = ".pm_require_cached.json"
_DENO_CACHE_TIMEOUT_S = 120.0


def pm_require_index_path(workspace: Path) -> Path:
    """Return the generated index path under *workspace*."""
    return workspace / _INDEX_NAME


def detect_npm_jsr_specs(script: str) -> list[PmRequireSpec]:
    """Return unique npm/jsr ``pm.require`` specs from *script* (invalid literals skipped)."""
    try:
        specs = _detect_pm_require_specs(script)
    except ValueError as exc:
        logger.debug("pm.require parse skipped for LSP types: %s", exc)
        return []
    return [s for s in specs if s.registry in ("npm", "jsr")]


def _read_cached_specifiers(workspace: Path) -> set[str]:
    path = workspace / _CACHE_STATE_NAME
    if not path.is_file():
        return set()
    try:
        parsed = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError, ValueError):
        return set()
    if not isinstance(parsed, list):
        return set()
    return {str(x) for x in parsed if x}


def _write_cached_specifiers(workspace: Path, specifiers: set[str]) -> None:
    path = workspace / _CACHE_STATE_NAME
    path.write_text(json.dumps(sorted(specifiers), indent=2) + "\n", encoding="utf-8")


def _write_workspace_npmrc(workspace: Path) -> None:
    npmrc_text, _extra = _build_npmrc_text()
    npmrc_path = workspace / ".npmrc"
    if not npmrc_text:
        if npmrc_path.is_file():
            with contextlib.suppress(OSError):
                npmrc_path.unlink()
        return
    npmrc_path.write_text(npmrc_text, encoding="utf-8")
    with contextlib.suppress(OSError):
        os.chmod(npmrc_path, 0o600)


def _deno_cache_specifiers(workspace: Path, specifiers: list[str]) -> None:
    """Best-effort ``deno cache`` for newly seen npm/jsr specifiers."""
    if not specifiers:
        return
    deno_path = RuntimeSettings.deno_path()
    if not deno_path or not Path(deno_path).is_file():
        return
    _write_workspace_npmrc(workspace)
    cache_root = _postmark_deno_user_cache_dir()
    deno_dir = cache_root / ".deno_dir"
    config = workspace / "deno.json"
    env = os.environ.copy()
    env["DENO_DIR"] = str(deno_dir)
    cmd = [
        deno_path,
        "cache",
        "--config",
        str(config),
        "--no-lock",
        *specifiers,
    ]
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=_DENO_CACHE_TIMEOUT_S,
            cwd=str(workspace),
            env=env,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        logger.debug("deno cache for pm.require types failed: %s", exc)
        return
    if result.returncode != 0:
        err = (result.stderr or result.stdout or "").strip()
        logger.debug("deno cache for pm.require types: %s", err or "non-zero exit")


def _render_index(specs: list[PmRequireSpec]) -> str:
    lines: list[str] = [
        "/** Auto-generated by Postmark — do not edit. */",
        "",
    ]
    if not specs:
        lines.append("// No pm.require npm/jsr specifiers detected.")
        lines.append("export {};")
        return "\n".join(lines) + "\n"

    imports: list[str] = []
    overloads: list[str] = []
    seen_import: set[str] = set()
    seen_overload: set[str] = set()

    for spec in sorted(specs, key=lambda s: s.specifier):
        var = f"__pm_req_{spec.ident}"
        if spec.specifier not in seen_import:
            seen_import.add(spec.specifier)
            imports.append(f'import type * as {var} from "{spec.specifier}";')
        if spec.specifier not in seen_overload:
            seen_overload.add(spec.specifier)
            overloads.append(
                f"  /** `{spec.specifier}` */\n"
                f'  function require(spec: "{spec.specifier}"): typeof {var};'
            )
        bare = f"{spec.registry}:{spec.name}"
        if bare != spec.specifier and bare not in seen_overload:
            seen_overload.add(bare)
            overloads.append(
                f'  /** `{bare}` */\n  function require(spec: "{bare}"): typeof {var};'
            )

    lines.extend(imports)
    lines.append("")
    lines.append("declare namespace pm {")
    lines.extend(overloads)
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def sync_pm_require_types(script: str, workspace: Path) -> bool:
    """Update ``pm_require_index.ts`` and cache missing npm/jsr specs.

    Returns ``True`` when the index file content changed.
    """
    if not RuntimeSettings.enable_npm_type_resolution():
        return False

    specs = detect_npm_jsr_specs(script)
    specifiers = {s.specifier for s in specs}
    cached = _read_cached_specifiers(workspace)
    missing = sorted(specifiers - cached)
    if missing:
        _deno_cache_specifiers(workspace, missing)
        _write_cached_specifiers(workspace, specifiers | cached)

    index_path = pm_require_index_path(workspace)
    new_text = _render_index(specs)
    old_text = index_path.read_text(encoding="utf-8") if index_path.is_file() else ""
    if new_text == old_text:
        return False
    index_path.write_text(new_text, encoding="utf-8")
    return True


__all__ = [
    "detect_npm_jsr_specs",
    "pm_require_index_path",
    "sync_pm_require_types",
]
