"""Generate ``pm_require_index.ts`` and cache npm/jsr specifiers for Deno LSP."""

from __future__ import annotations

import contextlib
import json
import logging
import os
import subprocess
import threading
from collections.abc import Callable
from pathlib import Path

from services.lsp.pm_require_resolve import (
    npm_types_specifier,
    primary_type_export_name,
    types_specifier,
)
from services.lsp.npm_types_members import types_dir_for_specifier
from services.scripting.deno_runtime import _build_npmrc_text, _postmark_deno_user_cache_dir
from services.scripting.js_runtime import PmRequireSpec, _detect_pm_require_specs
from services.scripting.local_script_modules import (
    LocalScriptModule,
    iter_pm_require_local_paths_js,
)
from services.scripting.runtime_settings import RuntimeSettings

logger = logging.getLogger(__name__)

_INDEX_NAME = "pm_require_index.ts"
_CACHE_STATE_NAME = ".pm_require_cached.json"
_DENO_CACHE_TIMEOUT_S = 120.0

# Per-process registry of which buffers contributed which specs to a workspace.
# Keyed by (resolved-workspace-path, buffer-uri); the index is the *union* of
# all entries so a buffer without npm/jsr requires can't wipe out the
# overloads another open buffer relies on.
_OPEN_BUFFER_SPECS: dict[tuple[str, str], list[PmRequireSpec]] = {}

# Parallel registry for ``pm.require('local:<rel>')`` rel-paths per buffer.
# Only paths that resolve to a real mirrored module are stored, so the
# generated ``typeof import('./local/<rel>')`` overloads never dangle.
_OPEN_BUFFER_LOCAL: dict[tuple[str, str], list[str]] = {}


def pm_require_index_path(workspace: Path) -> Path:
    """Return the generated index path under *workspace*."""
    return workspace / _INDEX_NAME


def detect_npm_jsr_specs(script: str) -> list[PmRequireSpec]:
    """Return unique npm/jsr ``pm.require`` specs from *script* (invalid literals skipped)."""
    try:
        specs = _detect_pm_require_specs(script)
    except ValueError as exc:
        logger.debug("pm.require parse skipped for LSP types: %s", exc)
        return []
    return [s for s in specs if s.registry in ("npm", "jsr")]


def _read_cached_specifiers(workspace: Path) -> set[str]:
    path = workspace / _CACHE_STATE_NAME
    if not path.is_file():
        return set()
    try:
        parsed = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError, ValueError):
        return set()
    if not isinstance(parsed, list):
        return set()
    return {str(x) for x in parsed if x}


def _write_cached_specifiers(workspace: Path, specifiers: set[str]) -> None:
    path = workspace / _CACHE_STATE_NAME
    path.write_text(json.dumps(sorted(specifiers), indent=2) + "\n", encoding="utf-8")


def _write_workspace_npmrc(workspace: Path) -> None:
    npmrc_text, _extra = _build_npmrc_text()
    npmrc_path = workspace / ".npmrc"
    if not npmrc_text:
        if npmrc_path.is_file():
            with contextlib.suppress(OSError):
                npmrc_path.unlink()
        return
    npmrc_path.write_text(npmrc_text, encoding="utf-8")
    with contextlib.suppress(OSError):
        os.chmod(npmrc_path, 0o600)


def _deno_cache_specifiers(workspace: Path, specifiers: list[str]) -> None:
    """Best-effort ``deno cache`` for newly seen npm/jsr specifiers."""
    if not specifiers:
        return
    deno_path = RuntimeSettings.deno_path()
    if not deno_path or not Path(deno_path).is_file():
        return
    _write_workspace_npmrc(workspace)
    cache_root = _postmark_deno_user_cache_dir()
    deno_dir = cache_root / ".deno_dir"
    config = workspace / "deno.json"
    env = os.environ.copy()
    env["DENO_DIR"] = str(deno_dir)
    cmd = [
        deno_path,
        "cache",
        "--config",
        str(config),
        "--no-lock",
        *specifiers,
    ]
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=_DENO_CACHE_TIMEOUT_S,
            cwd=str(workspace),
            env=env,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        logger.debug("deno cache for pm.require types failed: %s", exc)
        return
    if result.returncode != 0:
        err = (result.stderr or result.stdout or "").strip()
        logger.debug("deno cache for pm.require types: %s", err or "non-zero exit")


def _render_index(specs: list[PmRequireSpec], workspace: Path) -> str:
    local_rel_paths = _union_workspace_local(str(workspace.resolve()))
    lines: list[str] = [
        "/** Auto-generated by Postmark — do not edit. */",
        "",
    ]
    if not specs and not local_rel_paths:
        lines.append("// No pm.require npm/jsr/local specifiers detected.")
        lines.append("export {};")
        return "\n".join(lines) + "\n"

    imports: list[str] = []
    overloads: list[str] = []
    seen_import: set[str] = set()
    seen_overload: set[str] = set()

    for spec in sorted(specs, key=lambda s: s.specifier):
        types_npm = npm_types_specifier(spec)
        type_alias = f"__pm_types_{spec.ident}"
        if types_npm:
            types_dir = types_dir_for_specifier(workspace, types_npm)
            export_name = (
                primary_type_export_name(types_dir) if types_dir is not None else "default"
            )
            if types_npm not in seen_import:
                seen_import.add(types_npm)
                imports.append(
                    f'import type {{ {export_name} as {type_alias} }} from "{types_npm}";'
                )
            ret = type_alias
        else:
            typed_spec = types_specifier(spec)
            runtime_alias = f"__pm_req_{spec.ident}"
            if typed_spec not in seen_import:
                seen_import.add(typed_spec)
                imports.append(f'import type * as {runtime_alias} from "{typed_spec}";')
            ret = f"typeof {runtime_alias}"

        if spec.specifier not in seen_overload:
            seen_overload.add(spec.specifier)
            overloads.append(
                f"    /** `{spec.specifier}` */\n"
                f'    function require(spec: "{spec.specifier}"): {ret};'
            )
        bare = f"{spec.registry}:{spec.name}"
        if bare != spec.specifier and bare not in seen_overload:
            seen_overload.add(bare)
            overloads.append(f'    /** `{bare}` */\n    function require(spec: "{bare}"): {ret};')

    # ``pm.require('local:<rel>')`` → the mirrored module's namespace type.
    # ``rel`` includes the extension (e.g. ``home/tests/util.ts``); the inline
    # ``typeof import(...)`` resolves against the mirrored ``local/`` tree.
    for rel in sorted(set(local_rel_paths)):
        spec_lit = f"local:{rel}"
        if spec_lit in seen_overload:
            continue
        seen_overload.add(spec_lit)
        overloads.append(
            f"    /** `{spec_lit}` */\n"
            f'    function require(spec: "{spec_lit}"): typeof import("./local/{rel}");'
        )

    lines.extend(imports)
    lines.append("")
    lines.append("declare global {")
    lines.append("  namespace pm {")
    lines.extend(overloads)
    lines.append("  }")
    lines.append("}")
    lines.append("")
    lines.append("export {};")
    return "\n".join(lines) + "\n"


def _union_workspace_specs(workspace_key: str) -> list[PmRequireSpec]:
    """Return de-duplicated specs across every buffer registered for *workspace_key*."""
    union: dict[tuple[str, str, str], PmRequireSpec] = {}
    for (ws_key, _buffer_uri), specs in _OPEN_BUFFER_SPECS.items():
        if ws_key != workspace_key:
            continue
        for s in specs:
            union[(s.registry, s.name, s.version)] = s
    return list(union.values())


def _union_workspace_local(workspace_key: str) -> list[str]:
    """Return de-duplicated ``local:`` rel-paths across buffers for *workspace_key*."""
    union: set[str] = set()
    for (ws_key, _buffer_uri), rels in _OPEN_BUFFER_LOCAL.items():
        if ws_key == workspace_key:
            union.update(rels)
    return sorted(union)


def _mirror_and_filter_local(
    rel_paths: list[str],
    *,
    module_index: dict[str, LocalScriptModule] | None = None,
) -> list[str]:
    """Mirror the closure of *rel_paths* and return those that resolve to a module.

    Generating ``typeof import('./local/<rel>')`` only types correctly if the
    mirrored file (and its transitive ESM/``pm.require`` imports) exist on disk
    and the rel-path is a real module. Mirroring the full closure means a
    required module's own ``import '../sibling.js'`` resolves too. A broken
    transitive import degrades gracefully: we mirror the directly-required
    modules individually and still emit their overloads.
    """
    if not rel_paths:
        return []
    # Lazy imports avoid a circular import at module load (mirror →
    # services.lsp.servers._workspace → … → pm_require_types).
    from database.database import get_session
    from services.scripting.local_script_modules import (
        _resolve_required_from_index,
        build_module_index,
    )
    from services.scripting.local_scripts_project.mirror import (
        _should_mirror,
        _write_module,
        sync_closure,
    )

    if module_index is None:
        with get_session() as session:
            index = build_module_index(session)
    else:
        index = module_index
    synth = "\n".join(f'pm.require("local:{rel}");' for rel in rel_paths)
    try:
        sync_closure(_resolve_required_from_index(synth, "javascript", index))
    except ValueError:
        # Unresolvable transitive import somewhere in the closure — still mirror
        # the directly-required modules so their own exports type.
        for rel in rel_paths:
            mod = index.get(rel)
            if mod is not None and _should_mirror(mod):
                with contextlib.suppress(Exception):
                    _write_module(mod)
    return [rel for rel in rel_paths if rel in index]


def sync_pm_require_types(
    script: str,
    workspace: Path,
    *,
    buffer_uri: str = "",
    after_cache: Callable[[], None] | None = None,
    module_index: dict[str, LocalScriptModule] | None = None,
) -> bool:
    """Update ``pm_require_index.ts`` and cache missing npm/jsr specs.

    *buffer_uri* identifies the editor buffer whose contents are being
    sync'd. The generated index reflects the **union** of all buffers
    registered against the same workspace, so opening a script without
    any ``pm.require('npm:…')`` calls no longer wipes out the overloads
    another open buffer needs. Pass an empty string for one-off / test
    usage where buffer identity doesn't matter.

    Returns ``True`` when the index file content changed.
    """
    buffer_specs = detect_npm_jsr_specs(script)
    workspace_key = str(workspace.resolve())
    registry_key = (workspace_key, buffer_uri)
    if buffer_specs:
        _OPEN_BUFFER_SPECS[registry_key] = buffer_specs
    else:
        _OPEN_BUFFER_SPECS.pop(registry_key, None)

    local_valid = _mirror_and_filter_local(
        iter_pm_require_local_paths_js(script),
        module_index=module_index,
    )
    if local_valid:
        _OPEN_BUFFER_LOCAL[registry_key] = local_valid
    else:
        _OPEN_BUFFER_LOCAL.pop(registry_key, None)

    specs = _union_workspace_specs(workspace_key)
    specifiers: set[str] = set()
    for s in specs:
        specifiers.add(s.specifier)
        specifiers.add(types_specifier(s))
        types_npm = npm_types_specifier(s)
        if types_npm:
            specifiers.add(types_npm)
    cached = _read_cached_specifiers(workspace)
    missing = sorted(specifiers - cached)
    index_path = pm_require_index_path(workspace)
    new_text = _render_index(specs, workspace)
    old_text = index_path.read_text(encoding="utf-8") if index_path.is_file() else ""
    content_changed = new_text != old_text
    if content_changed:
        index_path.write_text(new_text, encoding="utf-8")

    if missing:

        def _cache_in_background() -> None:
            try:
                _deno_cache_specifiers(workspace, missing)
                _write_cached_specifiers(workspace, specifiers | cached)
            finally:
                if after_cache is not None:
                    after_cache()

        threading.Thread(target=_cache_in_background, daemon=True).start()

    return content_changed


def unregister_pm_require_buffer(workspace: Path, buffer_uri: str) -> None:
    """Drop *buffer_uri*'s contribution; called when an editor detaches."""
    key = (str(workspace.resolve()), buffer_uri)
    _OPEN_BUFFER_SPECS.pop(key, None)
    _OPEN_BUFFER_LOCAL.pop(key, None)


def sync_pm_require_closure_buffers(
    workspace: Path,
    buffers: list[tuple[str, str]],
    *,
    after_cache: Callable[[], None] | None = None,
) -> bool:
    """Register npm/jsr specs from every file in a local-script import closure.

    *buffers* is ``(file_uri, source)`` pairs (mirrored ``local/`` paths). Updates
    the workspace union index so siblings using ``pm.require('npm:…')`` keep types
    without a per-buffer preamble.
    """
    workspace_key = str(workspace.resolve())
    for uri, source in buffers:
        registry_key = (workspace_key, uri)
        specs = detect_npm_jsr_specs(source)
        if specs:
            _OPEN_BUFFER_SPECS[registry_key] = specs
        else:
            _OPEN_BUFFER_SPECS.pop(registry_key, None)

    specs = _union_workspace_specs(workspace_key)
    specifiers: set[str] = set()
    for s in specs:
        specifiers.add(s.specifier)
        specifiers.add(types_specifier(s))
        types_npm = npm_types_specifier(s)
        if types_npm:
            specifiers.add(types_npm)
    cached = _read_cached_specifiers(workspace)
    missing = sorted(specifiers - cached)
    index_path = pm_require_index_path(workspace)
    new_text = _render_index(specs, workspace)
    old_text = index_path.read_text(encoding="utf-8") if index_path.is_file() else ""
    content_changed = new_text != old_text
    if content_changed:
        index_path.write_text(new_text, encoding="utf-8")

    if missing:

        def _cache_in_background() -> None:
            try:
                _deno_cache_specifiers(workspace, missing)
                _write_cached_specifiers(workspace, specifiers | cached)
            finally:
                if after_cache is not None:
                    after_cache()

        threading.Thread(target=_cache_in_background, daemon=True).start()

    return content_changed


def _rewrite_workspace_index(workspace: Path) -> None:
    """Regenerate ``pm_require_index.ts`` from the current open-buffer registry."""
    workspace_key = str(workspace.resolve())
    specs = _union_workspace_specs(workspace_key)
    index_path = pm_require_index_path(workspace)
    index_path.write_text(_render_index(specs, workspace), encoding="utf-8")


def prune_orphan_specs(workspace: Path, live_keys: set[tuple[str, str]]) -> int:
    """Drop registry entries for *workspace* not in *live_keys*; rewrite the index.

    Returns the number of buffer entries removed.
    """
    workspace_key = str(workspace.resolve())
    orphans = {
        key
        for key in (*_OPEN_BUFFER_SPECS, *_OPEN_BUFFER_LOCAL)
        if key[0] == workspace_key and key not in live_keys
    }
    if not orphans:
        return 0
    for key in orphans:
        _OPEN_BUFFER_SPECS.pop(key, None)
        _OPEN_BUFFER_LOCAL.pop(key, None)
    _rewrite_workspace_index(workspace)
    return len(orphans)


def reset_workspace(workspace: Path) -> None:
    """Clear npm/jsr registry state for *workspace* and delete generated cache files."""
    workspace_key = str(workspace.resolve())
    for key in [k for k in _OPEN_BUFFER_SPECS if k[0] == workspace_key]:
        _OPEN_BUFFER_SPECS.pop(key, None)
    for key in [k for k in _OPEN_BUFFER_LOCAL if k[0] == workspace_key]:
        _OPEN_BUFFER_LOCAL.pop(key, None)
    for name in (_INDEX_NAME, _CACHE_STATE_NAME):
        path = workspace / name
        if path.is_file():
            with contextlib.suppress(OSError):
                path.unlink()
    _rewrite_workspace_index(workspace)


__all__ = [
    "detect_npm_jsr_specs",
    "pm_require_index_path",
    "prune_orphan_specs",
    "reset_workspace",
    "sync_pm_require_closure_buffers",
    "sync_pm_require_types",
    "unregister_pm_require_buffer",
]
