"""Generate ``pm.d.ts`` and ``pm.pyi`` from :mod:`services.scripting.pm_api_schema`."""

from __future__ import annotations

import ast
from pathlib import Path
from typing import Any

from services.scripting.pm_api_schema import PmNode, ROOTS


def _repo_root() -> Path:
    # stubs_generator.py → lsp → services → src → repo root
    return Path(__file__).resolve().parents[3]


def _walk(parts: list[str], node: PmNode, out: list[tuple[str, str]]) -> None:
    """Collect ``(dot_path, kind)`` for leaves.

    Empty namespaces (e.g. ``pm.response``, ``pm.request``) are emitted
    as ``any`` so user code can access arbitrary nested properties such
    as ``pm.response.to.have.status(...)`` without TS2339 errors. The
    schema marks these as free-form (see ``pm_api_schema.py``).
    """
    kind = node.get("kind", "namespace")
    children = node.get("children") or {}
    if kind == "function":
        out.append((".".join(parts), "function"))
        return
    if kind == "scope" and not children:
        out.append((".".join(parts), "scope"))
        return
    if kind == "namespace" and not children and parts:
        out.append((".".join(parts), "any"))
        return
    for name, child in children.items():
        _walk([*parts, name], child, out)  # type: ignore[arg-type]


def _ts_emit_tree(
    entries: list[tuple[str, str]],
    indent: str,
    *,
    npm_type_resolution: bool = True,
) -> list[str]:
    """Emit nested TypeScript namespaces from dotted paths."""
    tree: dict[str, Any] = {}

    def insert(parts: list[str], kind: str) -> None:
        cur: dict[str, Any] = tree
        for p in parts[:-1]:
            nxt = cur.setdefault(p, {})
            assert isinstance(nxt, dict)
            cur = nxt
        cur[parts[-1]] = kind

    for dotted, kind in entries:
        if dotted:
            insert(dotted.split("."), kind)

    lines: list[str] = []

    def emit(obj: dict[str, Any], pad: str) -> None:
        for key in sorted(obj.keys()):
            val = obj[key]
            if val == "function":
                lines.append(f"{pad}/** `{key}` */")
                if key == "require" and npm_type_resolution:
                    lines.append(
                        f"{pad}/** Fallback when specifier is not in pm_require_index.ts */"
                    )
                    lines.append(f"{pad}function {key}(spec: string): unknown;")
                else:
                    # ``any`` (not ``unknown``) so users can chain the
                    # result without explicit casts. The schema doesn't
                    # carry signatures, so type-checking the return value
                    # against an unknown shape would only produce noise.
                    lines.append(f"{pad}function {key}(...args: any[]): any;")
            elif val == "scope":
                lines.append(f"{pad}/** scope `{key}` */")
                lines.append(f"{pad}const {key}: Record<string, any>;")
            elif val == "any":
                # Free-form namespace (``pm.response``, ``pm.request`` …)
                # emitted as ``any`` so any deeper access type-checks.
                lines.append(f"{pad}/** free-form `{key}` */")
                lines.append(f"{pad}const {key}: any;")
            elif isinstance(val, dict):
                lines.append(f"{pad}namespace {key} {{")
                emit(val, pad + "  ")
                lines.append(f"{pad}}}")

    emit(tree, indent)
    return lines


def generate_ts(stubs_dir: Path, *, npm_type_resolution: bool = True) -> None:
    """Write ``pm.d.ts``.

    When *npm_type_resolution* is enabled, ``pm.require`` uses an
    ``unknown`` fallback so runtime overloads in ``pm_require_index.ts``
    can narrow literal specifiers. Otherwise the legacy ``any`` signature
    is emitted.
    """
    lines: list[str] = [
        "/** Generated by services.lsp.stubs_generator — do not edit. */",
        "",
    ]
    for root_name, root in ROOTS.items():
        entries: list[tuple[str, str]] = []
        _walk([], root, entries)
        lines.append(f"declare namespace {root_name} {{")
        lines.extend(_ts_emit_tree(entries, "  ", npm_type_resolution=npm_type_resolution))
        lines.append("}")
        lines.append("")
    stubs_dir.mkdir(parents=True, exist_ok=True)
    (stubs_dir / "pm.d.ts").write_text("\n".join(lines) + "\n", encoding="utf-8")


def generate_py(stubs_dir: Path) -> None:
    """Write ``pm.pyi``."""
    lines: list[str] = [
        '"""Generated by services.lsp.stubs_generator — do not edit."""',
        "from typing import Any",
        "",
        "class _Pm:",
    ]
    entries: list[tuple[str, str]] = []
    _walk([], ROOTS["pm"], entries)
    seen: set[str] = set()
    for path, kind in sorted(entries):
        if not path or path in seen:
            continue
        seen.add(path)
        parts = path.split(".")
        name = parts[-1]
        if kind == "function":
            lines.append(f"    def {name}(self, *args: Any, **kwargs: Any) -> Any: ...")
        elif kind == "scope":
            lines.append(f"    {name}: dict[str, Any]")
        elif kind == "any":
            lines.append(f"    {name}: Any")
    lines.append("")
    lines.append("pm: _Pm")
    stubs_dir.mkdir(parents=True, exist_ok=True)
    (stubs_dir / "pm.pyi").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    """CLI entry: ``python -m services.lsp.stubs_generator``."""
    root = _repo_root()
    out = root / "data" / "lsp" / "stubs"
    generate_ts(out)
    generate_py(out)
    ast.parse((out / "pm.pyi").read_text(encoding="utf-8"))
    print(f"Wrote {out / 'pm.d.ts'} and {out / 'pm.pyi'}")


if __name__ == "__main__":
    main()
