r"""Generic HMAC-SHA256 hex signature of ``METHOD\nURL``."""

from __future__ import annotations

from typing import Any

from services.ai.chat.tools.collection_draft.recipes.base import (
    SignatureRecipe,
    _str_field,
    register_recipe,
)

KIND = "hmac_sha256"


def _factory(overrides: dict[str, Any]) -> SignatureRecipe:
    """Build a recipe with optional header / variable name overrides."""
    key_header_raw = overrides.get("key_header")
    key_header = None if key_header_raw is None else str(key_header_raw).strip() or None
    return SignatureRecipe(
        kind=KIND,
        signature_header=_str_field(overrides, "signature_header", "X-Signature"),
        key_header=key_header,
        key_var=_str_field(overrides, "key_var", "apiKey"),
        secret_var=_str_field(overrides, "secret_var", "secret"),
        notes=(
            "X-Signature = HMAC-SHA256_hex(METHOD + '\\n' + URL, secret); "
            "URL is str(pm.request.url). This is a generic placeholder canonical "
            "form — adjust the recipe or script when a provider documents a "
            "different string-to-sign. Optionally sets an API-key header when "
            "key_header is configured."
        ),
    )


def _build_python(recipe: SignatureRecipe) -> str:
    """Emit RestrictedPython / Pyodide pre-request using sandbox shims."""
    lines = [
        f"# Generated by Postmark signature recipe: {recipe.kind}",
        f"# {recipe.notes}",
        f'secret = pm.variables.get("{recipe.secret_var}") or ""',
        'canonical = f"{pm.request.method}\\n{pm.request.url}"',
        "sig = hashlib_hmac_sha256(canonical, secret)",
        f'pm.request.headers["{recipe.signature_header}"] = sig',
    ]
    if recipe.key_header:
        lines.insert(
            3,
            f'api_key = pm.variables.get("{recipe.key_var}") or ""',
        )
        lines.append(f'pm.request.headers["{recipe.key_header}"] = api_key')
    return "\n".join(lines) + "\n"


def _build_javascript(recipe: SignatureRecipe) -> str:
    """Emit Deno / CryptoJS pre-request for the same algorithm."""
    lines = [
        f"// Generated by Postmark signature recipe: {recipe.kind}",
        f"// {recipe.notes}",
        f'const secret = pm.variables.get("{recipe.secret_var}") || "";',
        "const canonical = `${pm.request.method}\\n${pm.request.url}`;",
        "const sig = CryptoJS.HmacSHA256(canonical, secret).toString(CryptoJS.enc.Hex);",
        (f'pm.request.headers.upsert({{ key: "{recipe.signature_header}", value: sig }});'),
    ]
    if recipe.key_header:
        lines.insert(
            3,
            f'const apiKey = pm.variables.get("{recipe.key_var}") || "";',
        )
        lines.append(f'pm.request.headers.upsert({{ key: "{recipe.key_header}", value: apiKey }});')
    return "\n".join(lines) + "\n"


register_recipe(
    KIND,
    factory=_factory,
    build_python=_build_python,
    build_javascript=_build_javascript,
)

__all__ = ["KIND"]
