"""Hotelbeds-style plain SHA-256 of ``apiKey + secret + unixTimestamp``."""

from __future__ import annotations

from typing import Any

from services.ai.chat.tools.collection_draft.recipes.base import (
    SignatureRecipe,
    _str_field,
    register_recipe,
)

KIND = "sha256_apikey_secret_timestamp"


def _factory(overrides: dict[str, Any]) -> SignatureRecipe:
    """Build a recipe with optional header / variable name overrides."""
    return SignatureRecipe(
        kind=KIND,
        signature_header=_str_field(overrides, "signature_header", "X-Signature"),
        key_header=_str_field(overrides, "key_header", "Api-key"),
        key_var=_str_field(overrides, "key_var", "apiKey"),
        secret_var=_str_field(overrides, "secret_var", "secret"),
        notes=(
            "X-Signature = SHA256_hex(apiKey + secret + unixTimestampSeconds); "
            "also sets the API-key header."
        ),
    )


def _build_python(recipe: SignatureRecipe) -> str:
    """Emit RestrictedPython / Pyodide pre-request using sandbox shims."""
    key_h = recipe.key_header or "Api-key"
    return f'''\
# Generated by Postmark signature recipe: {recipe.kind}
# {recipe.notes}
api_key = pm.variables.get("{recipe.key_var}") or ""
secret = pm.variables.get("{recipe.secret_var}") or ""
ts = str(unix_timestamp())
sig = hashlib_sha256(api_key + secret + ts)
pm.request.headers["{key_h}"] = api_key
pm.request.headers["{recipe.signature_header}"] = sig
'''


def _build_javascript(recipe: SignatureRecipe) -> str:
    """Emit Deno / CryptoJS pre-request for the same algorithm."""
    key_h = recipe.key_header or "Api-key"
    return f'''\
// Generated by Postmark signature recipe: {recipe.kind}
// {recipe.notes}
const apiKey = pm.variables.get("{recipe.key_var}") || "";
const secret = pm.variables.get("{recipe.secret_var}") || "";
const ts = Math.floor(Date.now() / 1000).toString();
const sig = CryptoJS.SHA256(apiKey + secret + ts).toString(CryptoJS.enc.Hex);
pm.request.headers.upsert({{ key: "{key_h}", value: apiKey }});
pm.request.headers.upsert({{ key: "{recipe.signature_header}", value: sig }});
'''


register_recipe(
    KIND,
    factory=_factory,
    build_python=_build_python,
    build_javascript=_build_javascript,
)

__all__ = ["KIND"]
